services:

  github-config-server:
    image: 'demo/github-config-server:1.0.0'
    ports:
      - '8888:8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/eserver/default" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - GITHUB_TOKEN= # поставить свой

  eureka-server:
    image: 'demo/eureka-server:1.0.0'
    ports:
      - '8761:8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      github-config-server:
        condition: service_healthy

  api-gateway:
    image: 'demo/api-gateway:1.0.0'
    ports:
      - '8765:8765'
    depends_on:
      eureka-server:
        condition: service_healthy

  eureka-client:
    image: 'demo/eureka-client:1.0.0'
    ports:
      - '63443:63443'
    depends_on:
      eureka-server:
        condition: service_healthy

  eureka-client-2:
    image: 'demo/eureka-client-2:1.0.0'
    ports:
      - '63444:63444'
    depends_on:
      eureka-server:
        condition: service_healthy

